language: c
sudo: required
install: wget https://github.com/pierregobin/essai/blob/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.06
  - OCAML_VERSION=4.07
os:
  - linux
 
